# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "9229:9229"

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data:rw
    ports: 
      - '5432:5432'
